apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-service
  template:
    metadata:
      labels:
        app: bank-service
    spec:
      containers:
        - name: bank-service
          image: bank-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: bank-service-config

