apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: investment-service
  template:
    metadata:
      labels:
        app: investment-service
    spec:
      containers:
        - name: investment-service
          image: investment-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: investment-service-config

