# Archivo de configuración de Kubernetes para el Deployment de PostgreSQL utilizado por el servicio de inversiones.
apiVersion: apps/v1
kind: Deployment

# Metadatos del Deployment.
metadata:
  name: postgres-investment

# Especificación del Deployment, que define el número de réplicas, el selector de etiquetas y la plantilla del pod.
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-investment
  template:
    metadata:
      labels:
        app: postgres-investment

    # Especificación del contenedor que se ejecutará en el pod, incluyendo su nombre, imagen, puertos y variables de entorno.    
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432  
          env:
            - name: POSTGRES_DB
              value: investment_db
            - name: POSTGRES_USER
              value: investment_user
            - name: POSTGRES_PASSWORD
              value: investment_pass
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

      # Definición del volumen persistente para almacenar los datos de PostgreSQL.
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-investment-pvc
