# Archivo de configuración de Kubernetes para el Service que expone PostgreSQL utilizado por el servicio de inversiones.
apiVersion: v1
kind: Service

# Metadatos del Service.
metadata:
  name: postgres-investment

# Especificación del Service, que define el selector de etiquetas, los puertos expuestos y el tipo de Service.
spec:
  selector:
    app: postgres-investment
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
